import { v } from "convex/values";
import type { Doc, Id } from "./_generated/dataModel";
import type { MutationCtx, QueryCtx } from "./_generated/server";
import { internalMutation, internalQuery } from "./_generated/server";
import { buildInspectionHourKey, PRODUCTION_LINE_CHECK_KEYS } from "./productionLineRecordHelpers";
import {
  removeLabReportSummary,
  syncInspectionSummary,
  syncLabReportSummary,
  syncReadingFact,
  syncReviewCyclesFromEvents,
} from "./qualityReportingFacts";

const LEGACY_DEMO_PROJECT_NAME = "QC Reporting Demo Product";
const DEMO_PROJECT_DESCRIPTION =
  "Representative hourly production QC dataset generated by Playwright. Seed version 4.";
const DEMO_TIMEZONE = "Asia/Gaza";
const HOUR_MS = 60 * 60 * 1000;

const inspectors = [
  { id: "e2e-qc-inspector-ameer", name: "Ameer" },
  { id: "e2e-qc-inspector-qusai", name: "Qusai" },
  { id: "e2e-qc-inspector-shaima", name: "Shaima" },
] as const;

const products = ["Twin", "Rocky", "Daymeh", "Icy Lemon"] as const;

const reviewers = [
  { id: "e2e-qc-reviewer-maya", name: "Maya Saleh" },
  { id: "e2e-qc-reviewer-omar", name: "Omar Darwish" },
] as const;

const productionLines = [
  { departmentName: "BTC1", hall: "A" as const, productNames: ["Twin"] as const },
  { departmentName: "Rollo A", hall: "A" as const, productNames: ["Icy Lemon"] as const },
  {
    departmentName: "BTC2",
    hall: "B" as const,
    productNames: ["Daymeh", "Rocky"] as const,
  },
] as const;

const readingDefinitions = [
  { key: "pour_weight" as const, unit: "g" as const, minimum: 98, maximum: 102, target: 100 },
  { key: "additive_weight" as const, unit: "g" as const, minimum: 0.9, maximum: 1.1, target: 1 },
  {
    key: "chocolate_temperature" as const,
    unit: "°C" as const,
    minimum: 28,
    maximum: 32,
    target: 30,
  },
  {
    key: "coated_piece_weight" as const,
    unit: "g" as const,
    minimum: 18,
    maximum: 22,
    target: 20,
  },
  {
    key: "carton_weight" as const,
    unit: "kg" as const,
    minimum: 9.8,
    maximum: 10.2,
    target: 10,
  },
] as const;

function localDateParts(timestamp: number) {
  const parts = new Intl.DateTimeFormat("en-CA", {
    day: "2-digit",
    month: "2-digit",
    timeZone: DEMO_TIMEZONE,
    year: "numeric",
  }).formatToParts(new Date(timestamp));
  const value = (type: Intl.DateTimeFormatPartTypes) =>
    parts.find((part) => part.type === type)?.value ?? "";
  return { day: value("day"), month: value("month"), year: value("year") };
}

function batchFor(timestamp: number, sequence: number) {
  const { day, month, year } = localDateParts(timestamp);
  const date = `${year}-${month}-${day}`;
  const compact = `${day}${month}${year.slice(-2)}${sequence}`;
  return { compact, date, printed: `${compact.slice(0, 6)} ${sequence}` };
}

function statusFor(slotFromNewest: number, lineIndex: number) {
  if (slotFromNewest === 0) {
    return ["pending_production_review", "returned", "draft"][
      lineIndex
    ] as Doc<"productionLineRecords">["status"];
  }
  if (slotFromNewest === 1) {
    return ["approved", "pending_production_review", "returned"][
      lineIndex
    ] as Doc<"productionLineRecords">["status"];
  }
  if (slotFromNewest === 2) {
    return ["draft", "approved", "pending_production_review"][
      lineIndex
    ] as Doc<"productionLineRecords">["status"];
  }
  if (slotFromNewest === 3) {
    return ["pending_production_review", "returned", "draft"][
      lineIndex
    ] as Doc<"productionLineRecords">["status"];
  }
  return "approved";
}

export const seedResultValidator = v.object({
  seeded: v.boolean(),
  organizationId: v.id("organizations"),
  projectId: v.id("projects"),
  inspections: v.number(),
  inspectors: v.number(),
  productionLines: v.number(),
  samples: v.number(),
  labReports: v.number(),
});

export type SeedResult = {
  seeded: boolean;
  organizationId: Id<"organizations">;
  projectId: Id<"projects">;
  inspections: number;
  inspectors: number;
  productionLines: number;
  samples: number;
  labReports: number;
};

async function existingSeedResult(
  ctx: QueryCtx | MutationCtx,
  organizationId: Id<"organizations">,
  projectIds: Id<"projects">[],
): Promise<SeedResult> {
  const projectIdSet = new Set(projectIds);
  const records = await ctx.db
    .query("productionLineRecords")
    .withIndex("by_organizationId", (q) => q.eq("organizationId", organizationId))
    .take(500);
  const [sampleGroups, reportGroups] = await Promise.all([
    Promise.all(
      projectIds.map((projectId) =>
        ctx.db
          .query("labSampleSubmissions")
          .withIndex("by_organizationId_and_projectId_and_sampledAt", (q) =>
            q.eq("organizationId", organizationId).eq("projectId", projectId),
          )
          .take(100),
      ),
    ),
    Promise.all(
      projectIds.map((projectId) =>
        ctx.db
          .query("labReports")
          .withIndex("by_projectId", (q) => q.eq("projectId", projectId))
          .take(100),
      ),
    ),
  ]);
  const projectRecords = records.filter((record) => projectIdSet.has(record.productId));
  return {
    seeded: false,
    organizationId,
    projectId: projectIds[0],
    inspections: projectRecords.length,
    inspectors: new Set(projectRecords.map((record) => record.qcUserId)).size,
    productionLines: new Set(projectRecords.map((record) => record.departmentName)).size,
    samples: sampleGroups.flat().length,
    labReports: reportGroups.flat().length,
  };
}

async function findDemoOrganization(ctx: QueryCtx | MutationCtx, organizationName: string) {
  if (!organizationName.startsWith("E2E ")) {
    throw new Error("QC report demo data can only be written to an E2E organization");
  }
  const matchingOrganizations = (await ctx.db.query("organizations").take(500)).filter(
    (organization) => organization.name === organizationName,
  );
  if (matchingOrganizations.length !== 1) {
    throw new Error("Expected exactly one E2E QC reporting organization");
  }
  return matchingOrganizations[0];
}

async function getDemoRecords(
  ctx: QueryCtx | MutationCtx,
  organizationId: Id<"organizations">,
  projectIds: Id<"projects">[],
) {
  const projectIdSet = new Set(projectIds);
  return (
    await ctx.db
      .query("productionLineRecords")
      .withIndex("by_organizationId", (q) => q.eq("organizationId", organizationId))
      .take(500)
  ).filter((record) => projectIdSet.has(record.productId));
}

function seedIsCurrent(
  demoProjects: Doc<"projects">[],
  records: Doc<"productionLineRecords">[],
  now: number,
) {
  const newestInspectionAt = Math.max(...records.map((record) => record.inspectionAt), 0);
  return (
    demoProjects.length === products.length &&
    demoProjects.every((project) => project.description === DEMO_PROJECT_DESCRIPTION) &&
    records.length === 36 &&
    newestInspectionAt >= now - 2 * HOUR_MS
  );
}

async function removeStaleDemoData(
  ctx: MutationCtx,
  organizationId: Id<"organizations">,
  project: Doc<"projects">,
  storageIds: Set<Id<"_storage">>,
) {
  const records = await getDemoRecords(ctx, organizationId, [project._id]);
  for (const record of records) {
    if (record.batchLabelPhotoStorageId) {
      storageIds.add(record.batchLabelPhotoStorageId);
    }
    const [readings, checks, events, readingFacts, reviewCycles, summary] = await Promise.all([
      ctx.db
        .query("productionLineReadings")
        .withIndex("by_recordId", (q) => q.eq("recordId", record._id))
        .take(100),
      ctx.db
        .query("productionLineChecks")
        .withIndex("by_recordId", (q) => q.eq("recordId", record._id))
        .take(100),
      ctx.db
        .query("productionLineRecordEvents")
        .withIndex("by_recordId", (q) => q.eq("recordId", record._id))
        .take(100),
      ctx.db
        .query("qualityReadingFacts")
        .withIndex("by_recordId", (q) => q.eq("recordId", record._id))
        .take(100),
      ctx.db
        .query("qualityReviewCycles")
        .withIndex("by_recordId_and_cycleNumber", (q) => q.eq("recordId", record._id))
        .take(20),
      ctx.db
        .query("qualityInspectionSummaries")
        .withIndex("by_recordId", (q) => q.eq("recordId", record._id))
        .unique(),
    ]);
    for (const document of [...readingFacts, ...reviewCycles, ...readings, ...checks, ...events]) {
      await ctx.db.delete(document._id);
    }
    if (summary) {
      await ctx.db.delete(summary._id);
    }
    await ctx.db.delete(record._id);
  }

  const reports = await ctx.db
    .query("labReports")
    .withIndex("by_projectId", (q) => q.eq("projectId", project._id))
    .take(100);
  for (const report of reports) {
    const results = await ctx.db
      .query("labTestResults")
      .withIndex("by_labReportId", (q) => q.eq("labReportId", report._id))
      .take(100);
    await removeLabReportSummary(ctx, report._id);
    for (const result of results) {
      await ctx.db.delete(result._id);
    }
    await ctx.db.delete(report._id);
    await ctx.db.delete(report.runId);
  }

  const samples = await ctx.db
    .query("labSampleSubmissions")
    .withIndex("by_organizationId_and_projectId_and_sampledAt", (q) =>
      q.eq("organizationId", organizationId).eq("projectId", project._id),
    )
    .take(100);
  for (const sample of samples) {
    await ctx.db.delete(sample._id);
  }

  const specifications = await ctx.db
    .query("productionLineSpecifications")
    .withIndex("by_organizationId_and_productId", (q) =>
      q.eq("organizationId", organizationId).eq("productId", project._id),
    )
    .take(20);
  for (const specification of specifications) {
    const limits = await ctx.db
      .query("productionLineSpecificationLimits")
      .withIndex("by_specificationId_and_readingKey", (q) =>
        q.eq("specificationId", specification._id),
      )
      .take(20);
    for (const limit of limits) {
      await ctx.db.delete(limit._id);
    }
    await ctx.db.delete(specification._id);
  }
  await ctx.db.delete(project._id);
}

export const getExistingSeed = internalQuery({
  args: {
    organizationName: v.string(),
    confirmation: v.literal("seed-e2e-qc-reporting-demo"),
    now: v.number(),
  },
  returns: v.union(seedResultValidator, v.null()),
  handler: async (ctx, args): Promise<SeedResult | null> => {
    const organization = await findDemoOrganization(ctx, args.organizationName);
    const projects = await ctx.db
      .query("projects")
      .withIndex("by_organizationId", (q) => q.eq("organizationId", organization._id))
      .take(100);
    const demoProjects = products
      .map((productName) => projects.find((project) => project.name === productName))
      .filter((project): project is Doc<"projects"> => project !== undefined);
    if (demoProjects.length !== products.length) {
      return null;
    }
    const projectIds = demoProjects.map((project) => project._id);
    const records = await getDemoRecords(ctx, organization._id, projectIds);
    return seedIsCurrent(demoProjects, records, args.now)
      ? await existingSeedResult(ctx, organization._id, projectIds)
      : null;
  },
});

/**
 * Persistent development fixture invoked by the Playwright QC-report demo test.
 * It is internal-only and refuses to write into organizations without an E2E name.
 */
export const seedQualityReports = internalMutation({
  args: {
    organizationName: v.string(),
    confirmation: v.literal("seed-e2e-qc-reporting-demo"),
    evidenceImage: v.id("_storage"),
    now: v.number(),
  },
  returns: seedResultValidator,
  handler: async (ctx, args): Promise<SeedResult> => {
    const organization = await findDemoOrganization(ctx, args.organizationName);
    const projects = await ctx.db
      .query("projects")
      .withIndex("by_organizationId", (q) => q.eq("organizationId", organization._id))
      .take(100);
    const demoProjectNames = new Set<string>([...products, LEGACY_DEMO_PROJECT_NAME]);
    const demoProjects = projects.filter((project) => demoProjectNames.has(project.name));
    const currentProjects = products
      .map((productName) => projects.find((project) => project.name === productName))
      .filter((project): project is Doc<"projects"> => project !== undefined);
    if (currentProjects.length === products.length) {
      const projectIds = currentProjects.map((project) => project._id);
      const records = await getDemoRecords(ctx, organization._id, projectIds);
      if (seedIsCurrent(currentProjects, records, args.now)) {
        return await existingSeedResult(ctx, organization._id, projectIds);
      }
    }
    const staleStorageIds = new Set<Id<"_storage">>();
    for (const demoProject of demoProjects) {
      await removeStaleDemoData(ctx, organization._id, demoProject, staleStorageIds);
    }
    for (const storageId of staleStorageIds) {
      await ctx.storage.delete(storageId);
    }

    const now = args.now;
    const settings = await ctx.db
      .query("productionLineSettings")
      .withIndex("by_organizationId", (q) => q.eq("organizationId", organization._id))
      .unique();
    if (settings) {
      await ctx.db.patch(settings._id, {
        enabledHallCodes: ["A", "B"],
        timezone: DEMO_TIMEZONE,
        updatedAt: now,
        updatedBy: organization.ownerId,
      });
    } else {
      await ctx.db.insert("productionLineSettings", {
        organizationId: organization._id,
        enabledHallCodes: ["A", "B"],
        timezone: DEMO_TIMEZONE,
        updatedAt: now,
        updatedBy: organization.ownerId,
      });
    }

    for (const hallCode of ["A", "B"] as const) {
      const existingCounter = await ctx.db
        .query("productionLineSerialCounters")
        .withIndex("by_organizationId_and_hallCode", (q) =>
          q.eq("organizationId", organization._id).eq("hallCode", hallCode),
        )
        .unique();
      if (!existingCounter) {
        await ctx.db.insert("productionLineSerialCounters", {
          organizationId: organization._id,
          hallCode,
          nextSequence: hallCode === "A" ? 2037 : 1019,
          initializedAt: now,
          initializedBy: organization.ownerId,
        });
      }
    }

    const seededProducts: Array<{
      name: (typeof products)[number];
      projectId: Id<"projects">;
      specificationId: Id<"productionLineSpecifications">;
    }> = [];
    for (const productName of products) {
      const projectId = await ctx.db.insert("projects", {
        name: productName,
        version: "1.0",
        status: "Released",
        lead: "Quality Demonstration Team",
        description: DEMO_PROJECT_DESCRIPTION,
        ingredients: [],
        organizationId: organization._id,
        userId: organization.ownerId,
      });
      const specificationId = await ctx.db.insert("productionLineSpecifications", {
        organizationId: organization._id,
        productId: projectId,
        productName,
        version: 1,
        status: "active",
        createdAt: now - 30 * 24 * HOUR_MS,
        createdBy: organization.ownerId,
        effectiveAt: now - 29 * 24 * HOUR_MS,
        publishedBy: organization.ownerId,
      });
      for (const definition of readingDefinitions) {
        await ctx.db.insert("productionLineSpecificationLimits", {
          specificationId,
          readingKey: definition.key,
          unit: definition.unit,
          minimum: definition.minimum,
          maximum: definition.maximum,
          target: definition.target,
          minimumReadingCount: 1,
        });
      }
      seededProducts.push({ name: productName, projectId, specificationId });
    }

    const newestHour = Math.floor(now / HOUR_MS) * HOUR_MS;
    const firstHour = newestHour - 11 * HOUR_MS;
    const sampleCandidates: Array<{
      productionNumber: string;
      sampledAt: number;
      line: string;
      product: (typeof seededProducts)[number];
    }> = [];
    let serialA = 2001;
    let serialB = 1001;

    for (let hourIndex = 0; hourIndex < 12; hourIndex += 1) {
      const inspectionAt = firstHour + hourIndex * HOUR_MS;
      const slotFromNewest = 11 - hourIndex;
      for (let lineIndex = 0; lineIndex < productionLines.length; lineIndex += 1) {
        const line = productionLines[lineIndex];
        const productName = line.productNames[hourIndex % line.productNames.length];
        const product = seededProducts.find((candidate) => candidate.name === productName);
        if (!product) {
          throw new Error(`Could not resolve seeded product ${productName}`);
        }
        const batchSequence = products.indexOf(product.name) + 1;
        const batch = batchFor(inspectionAt, batchSequence);
        const inspector = inspectors[(hourIndex + lineIndex) % inspectors.length];
        const status = statusFor(slotFromNewest, lineIndex);
        const isIncomplete = status === "draft" || status === "returned";
        const outOfLimit = (hourIndex * productionLines.length + lineIndex) % 7 === 0;
        const createdAt = inspectionAt + 5 * 60_000;
        const submittedAt = createdAt + 12 * 60_000;
        const reviewedAt = submittedAt + (18 + lineIndex * 7) * 60_000;
        const serialSequence = line.hall === "A" ? serialA++ : serialB++;
        const displaySerial = `${line.hall} ${serialSequence}`;
        const recordRevision =
          status === "draft" ? 2 : status === "pending_production_review" ? 4 : 5;
        const recordId = await ctx.db.insert("productionLineRecords", {
          organizationId: organization._id,
          productionHallCode: line.hall,
          serialSequence,
          displaySerial,
          departmentName: line.departmentName,
          productId: product.projectId,
          productName: product.name,
          inspectionAt,
          inspectionHourKey: buildInspectionHourKey(inspectionAt, DEMO_TIMEZONE),
          specificationId: product.specificationId,
          specificationVersion: 1,
          batchLabelPhotoStorageId: isIncomplete ? undefined : args.evidenceImage,
          batchLabelMimeType: isIncomplete ? undefined : "image/svg+xml",
          batchLabelSize: isIncomplete ? undefined : 640,
          batchLabelCapturedAt: isIncomplete ? undefined : createdAt + 2 * 60_000,
          printedBatchCode: isIncomplete && lineIndex === 2 ? undefined : batch.printed,
          labelProductionDate: isIncomplete && lineIndex === 2 ? undefined : batch.date,
          dailyBatchSequence: isIncomplete && lineIndex === 2 ? undefined : batchSequence,
          batchLabelConfirmedBy: isIncomplete && lineIndex === 2 ? undefined : inspector.id,
          batchLabelConfirmedAt:
            isIncomplete && lineIndex === 2 ? undefined : createdAt + 4 * 60_000,
          status,
          editableOwnerUserId: inspector.id,
          qcUserId: inspector.id,
          qcUserName: inspector.name,
          recordRevision,
          createdAt,
          updatedAt:
            status === "draft"
              ? createdAt + 8 * 60_000
              : status === "pending_production_review"
                ? submittedAt
                : reviewedAt,
        });

        await ctx.db.insert("productionLineRecordEvents", {
          recordId,
          organizationId: organization._id,
          action: "record.created",
          actorId: inspector.id,
          actorName: inspector.name,
          recordRevision: 1,
          metadata: { displaySerial },
          createdAt,
        });
        if (!isIncomplete) {
          await ctx.db.insert("productionLineRecordEvents", {
            recordId,
            organizationId: organization._id,
            action: "batch_label.photo_attached",
            actorId: inspector.id,
            actorName: inspector.name,
            recordRevision: 2,
            createdAt: createdAt + 2 * 60_000,
          });
        }
        if (status !== "draft") {
          await ctx.db.insert("productionLineRecordEvents", {
            recordId,
            organizationId: organization._id,
            action: "record.submitted_for_review",
            actorId: inspector.id,
            actorName: inspector.name,
            recordRevision: 4,
            metadata: { status: "pending_production_review" },
            createdAt: submittedAt,
          });
        }
        if (status === "approved" || status === "returned") {
          const reviewer = reviewers[(hourIndex + lineIndex) % reviewers.length];
          await ctx.db.insert("productionLineRecordEvents", {
            recordId,
            organizationId: organization._id,
            action: status === "approved" ? "record.approved" : "record.returned",
            actorId: reviewer.id,
            actorName: reviewer.name,
            recordRevision: 5,
            metadata:
              status === "returned" ? { note: "Recheck evidence and measurement." } : undefined,
            createdAt: reviewedAt,
          });
        }

        for (let readingIndex = 0; readingIndex < readingDefinitions.length; readingIndex += 1) {
          const definition = readingDefinitions[readingIndex];
          const varianceStep = ((hourIndex + lineIndex + readingIndex) % 5) - 2;
          const normalValue =
            definition.target + varianceStep * (definition.maximum - definition.minimum) * 0.08;
          const value =
            definition.key === "pour_weight" && outOfLimit ? 103.4 + lineIndex * 0.2 : normalValue;
          const readingId = await ctx.db.insert("productionLineReadings", {
            recordId,
            readingKey: definition.key,
            readingIndex: 1,
            value,
            unit: definition.unit,
            minimum: definition.minimum,
            maximum: definition.maximum,
            target: definition.target,
            withinLimit: value >= definition.minimum && value <= definition.maximum,
            observedAt: createdAt + (5 + readingIndex) * 60_000,
            observedBy: inspector.id,
            updatedAt: createdAt + (5 + readingIndex) * 60_000,
          });
          await syncReadingFact(ctx, readingId);
        }

        const includedChecks = isIncomplete
          ? PRODUCTION_LINE_CHECK_KEYS.slice(0, PRODUCTION_LINE_CHECK_KEYS.length - 3)
          : PRODUCTION_LINE_CHECK_KEYS;
        for (const checkKey of includedChecks) {
          await ctx.db.insert("productionLineChecks", {
            recordId,
            checkKey,
            checked: true,
            updatedAt: createdAt + 10 * 60_000,
            updatedBy: inspector.id,
          });
        }
        const completedRecord = await ctx.db.get(recordId);
        if (!completedRecord) {
          throw new Error("Could not read the seeded QC record");
        }
        await syncReviewCyclesFromEvents(ctx, completedRecord);
        await syncInspectionSummary(ctx, recordId);
        sampleCandidates.push({
          productionNumber: batch.compact,
          sampledAt: inspectionAt + 35 * 60_000,
          line: line.departmentName,
          product,
        });
      }
    }

    const candidateEntries = sampleCandidates.slice(-8);
    const sampleIds: Id<"labSampleSubmissions">[] = [];
    for (let index = 0; index < candidateEntries.length; index += 1) {
      const candidate = candidateEntries[index];
      const submitter = inspectors[index % inspectors.length];
      const sampleId = await ctx.db.insert("labSampleSubmissions", {
        organizationId: organization._id,
        sampleType: "final_product",
        sampleYear: Number(localDateParts(candidate.sampledAt).year),
        serialSequence: index + 1,
        sampleNumber: `F${localDateParts(candidate.sampledAt).year.slice(-2)}${String(index + 1).padStart(4, "0")}`,
        projectId: candidate.product.projectId,
        productName: candidate.product.name,
        productionNumber: candidate.productionNumber,
        sampleLocation: candidate.line,
        sampledAt: candidate.sampledAt,
        notes: "Hourly finished-product retention sample.",
        submittedBy: submitter.id,
        submittedByName: submitter.name,
        createdAt: candidate.sampledAt,
      });
      sampleIds.push(sampleId);
    }

    const labStatuses = [
      "Approved",
      "Approved",
      "Failed",
      "Pending",
      "Approved",
      "Approved",
    ] as const;
    for (let index = 0; index < labStatuses.length; index += 1) {
      const sampleId = sampleIds[index];
      if (!sampleId) {
        throw new Error("Could not resolve the seeded laboratory sample");
      }
      const sample = await ctx.db.get(sampleId);
      if (!sample?.projectId) {
        throw new Error("Could not read the seeded laboratory sample");
      }
      const runId = await ctx.db.insert("runs", {
        projectId: sample.projectId,
        projectName: sample.productName,
        batchCode: sample.productionNumber,
        startTime: sample.sampledAt - HOUR_MS,
        endTime: sample.sampledAt - 20 * 60_000,
        durationString: "00:40:00",
        data: {},
        status: "completed",
        runOutcome: "success",
        userId: organization.ownerId,
        organizationId: organization._id,
      });
      const status = labStatuses[index];
      const reportId = await ctx.db.insert("labReports", {
        reportId: `QC-DEMO-${String(index + 1).padStart(3, "0")}`,
        runId,
        sampleSubmissionId: sample._id,
        projectId: sample.projectId,
        projectName: sample.productName,
        version: "1.0",
        lotNumber: sample.productionNumber,
        date: new Date(now).toISOString(),
        status,
        leadChemist: index % 2 === 0 ? "Rana Masri" : "Yousef Hamdan",
        sampleType: "Finished Product",
        hash: `e2e-qc-demo-${index + 1}`,
        userId: organization.ownerId,
        organizationId: organization._id,
        signedBy: status === "Approved" ? reviewers[index % reviewers.length].id : undefined,
        signedAt: status === "Approved" ? now : undefined,
      });
      const testResults = [
        {
          parameter: "Moisture",
          method: "Oven",
          min: 0,
          max: 5,
          actualValue: status === "Failed" ? 6.4 : 3.2 + index * 0.1,
          unit: "%",
        },
        {
          parameter: "pH",
          method: "Electrode",
          min: 6.5,
          max: 7.5,
          actualValue: status === "Failed" ? 8.1 : 6.9 + (index % 3) * 0.1,
          unit: "pH",
        },
        {
          parameter: "Viscosity",
          method: "Brookfield",
          min: 1000,
          max: 1400,
          actualValue: 1160 + index * 22,
          unit: "cP",
        },
      ];
      for (let resultIndex = 0; resultIndex < testResults.length; resultIndex += 1) {
        await ctx.db.insert("labTestResults", {
          labReportId: reportId,
          sortOrder: resultIndex,
          ...testResults[resultIndex],
        });
      }
      await syncLabReportSummary(ctx, reportId);
    }

    return {
      seeded: true,
      organizationId: organization._id,
      projectId: seededProducts[0].projectId,
      inspections: 12 * productionLines.length,
      inspectors: inspectors.length,
      productionLines: productionLines.length,
      samples: sampleIds.length,
      labReports: labStatuses.length,
    };
  },
});
